inference:

  router:
    type: k9

  llm_factory:
    provider: ollama
    base_url: http://192.168.1.98:11434

    models:
      general: llama3.2:1b

  model_catalog:
    default_model: general

    models:
      general:
        provider: ollama
        llm_ref: general
        capabilities: [chat]