# SPDX-License-Identifier: LicenseRef-K9AIF-Proprietary
# Generated by K9-AIF Generator (Updated)

"""
AcmeSupportCenter — K9-AIF Application
"""

from examples.acme_support_center.utils.bootstrap import ACMESupportBootstrap


def main() -> None:
    bootstrap = ACMESupportBootstrap()
    bootstrap.initialize()

    orchestrator = bootstrap.get_orchestrator("support_orchestrator")
    result = orchestrator.start(
        squads=bootstrap.squads,
        context={"config": bootstrap.config},
    )

    triage = result.get("triage_result", {}).get("triage", {})
    final = (
        result.get("final_result", {}).get("final_response")
        or result.get("quality_result", {}).get("final_response")
        or result.get("resolution_result", {}).get("resolution")
        or "No response available."
    )

    print("\n----------------------------------")
    print(f"Intent   : {triage.get('intent', 'n/a')}")
    print(f"Category : {triage.get('category', 'n/a')}")
    print(f"Priority : {triage.get('priority', 'n/a')}")
    print("\nResponse:")
    print(final)
    print("----------------------------------\n")


if __name__ == "__main__":
    main()