# SPDX-License-Identifier: Apache-2.0
# K9-AIF Framework

# Generated by K9-AIF Generator on 2026-03-16 15:03:01

import pytest
from k9_projects.acme_support_center.main import main
from k9_projects.acme_support_center.orchestrators.default_orchestrator import AcmeSupportCenterOrchestrator


def test_main_runs():
    """Ensure the main entrypoint runs without errors."""
    try:
        main()
    except Exception as e:
        pytest.fail(f"App AcmeSupportCenter failed to run: {e}")


def test_orchestrator_execute_flow():
    """Ensure the orchestrator execute_flow() method returns the expected stub result."""
    orch = AcmeSupportCenterOrchestrator({})
    result = orch.execute_flow({"query": "test"})

    assert isinstance(result, dict)
    assert result.get("status") == "ok"
    assert result.get("response") == "Hello World from K9-AIF Application Stub"
