-- DROP SCHEMA eoc;

CREATE SCHEMA eoc AUTHORIZATION postgres;

-- DROP SEQUENCE eoc.context_artifacts_id_seq;

CREATE SEQUENCE eoc.context_artifacts_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE eoc.routing_decisions_id_seq;

CREATE SEQUENCE eoc.routing_decisions_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE eoc.session_turns_id_seq;

CREATE SEQUENCE eoc.session_turns_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- eoc.audit_entries definition

-- Drop table

-- DROP TABLE eoc.audit_entries;

CREATE TABLE eoc.audit_entries (
	audit_id text NOT NULL,
	event_id text NOT NULL,
	event_type text NOT NULL,
	squad_id text NULL,
	agent_name text NOT NULL,
	model_id text NULL,
	model_provider text NULL,
	model_version text NULL,
	prompt_hash text NULL,
	response_hash text NULL,
	confidence_score float8 NULL,
	disposition text NULL,
	governance_checks jsonb NULL,
	timestamp_utc timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	session_id text NULL,
	correlation_id text NOT NULL,
	operator_id text NULL,
	CONSTRAINT audit_entries_pkey PRIMARY KEY (audit_id)
);
CREATE INDEX idx_audit_agent ON eoc.audit_entries USING btree (agent_name);
CREATE INDEX idx_audit_correlation ON eoc.audit_entries USING btree (correlation_id);
CREATE INDEX idx_audit_event ON eoc.audit_entries USING btree (event_id);
CREATE INDEX idx_audit_timestamp ON eoc.audit_entries USING btree (timestamp_utc);


-- eoc.claimants definition

-- Drop table

-- DROP TABLE eoc.claimants;

CREATE TABLE eoc.claimants (
	claimant_id text NOT NULL,
	"name" text NOT NULL,
	email text NULL,
	phone text NULL,
	ssn_hash text NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT claimants_pkey PRIMARY KEY (claimant_id)
);


-- eoc.escalation_tickets definition

-- Drop table

-- DROP TABLE eoc.escalation_tickets;

CREATE TABLE eoc.escalation_tickets (
	ticket_id text NOT NULL,
	event_id text NULL,
	event_type text NULL,
	squad_id text NULL,
	agent_name text NULL,
	reason text NOT NULL,
	confidence_score float8 NULL,
	context_payload jsonb NULL,
	agent_rationale text NULL,
	priority text DEFAULT 'normal'::text NULL,
	status text DEFAULT 'open'::text NULL,
	assigned_operator text NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	resolved_at timestamp NULL,
	resolution_notes text NULL,
	correlation_id text NULL,
	CONSTRAINT escalation_tickets_pkey PRIMARY KEY (ticket_id)
);
CREATE INDEX idx_escalation_correlation ON eoc.escalation_tickets USING btree (correlation_id);
CREATE INDEX idx_escalation_status ON eoc.escalation_tickets USING btree (status);


-- eoc.sessions definition

-- Drop table

-- DROP TABLE eoc.sessions;

CREATE TABLE eoc.sessions (
	session_id text NOT NULL,
	user_id text NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	last_active timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	model_affinity text NULL,
	CONSTRAINT sessions_pkey PRIMARY KEY (session_id)
);


-- eoc.context_artifacts definition

-- Drop table

-- DROP TABLE eoc.context_artifacts;

CREATE TABLE eoc.context_artifacts (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	session_id text NOT NULL,
	artifact_key text NULL,
	artifact_val text NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT context_artifacts_pkey PRIMARY KEY (id),
	CONSTRAINT context_artifacts_session_id_fkey FOREIGN KEY (session_id) REFERENCES eoc.sessions(session_id)
);


-- eoc.policies definition

-- Drop table

-- DROP TABLE eoc.policies;

CREATE TABLE eoc.policies (
	policy_id text NOT NULL,
	claimant_id text NULL,
	policy_type text NOT NULL,
	coverage_amount numeric(14, 2) NULL,
	deductible numeric(14, 2) NULL,
	status text DEFAULT 'active'::text NULL,
	effective_date date NULL,
	expiry_date date NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT policies_pkey PRIMARY KEY (policy_id),
	CONSTRAINT policies_claimant_id_fkey FOREIGN KEY (claimant_id) REFERENCES eoc.claimants(claimant_id)
);


-- eoc.session_turns definition

-- Drop table

-- DROP TABLE eoc.session_turns;

CREATE TABLE eoc.session_turns (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	session_id text NOT NULL,
	"role" text NOT NULL,
	"content" text NULL,
	token_count int4 NULL,
	compressed bool DEFAULT false NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT session_turns_pkey PRIMARY KEY (id),
	CONSTRAINT session_turns_session_id_fkey FOREIGN KEY (session_id) REFERENCES eoc.sessions(session_id)
);


-- eoc.claims definition

-- Drop table

-- DROP TABLE eoc.claims;

CREATE TABLE eoc.claims (
	claim_id text NOT NULL,
	claimant_id text NULL,
	policy_id text NULL,
	event_id text NULL,
	claim_type text NULL,
	amount_claimed numeric(14, 2) NULL,
	priority text DEFAULT 'normal'::text NULL,
	status text DEFAULT 'submitted'::text NULL,
	completeness_score float8 NULL,
	coverage_match bool NULL,
	submitted_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	notes text NULL,
	correlation_id text NULL,
	CONSTRAINT claims_pkey PRIMARY KEY (claim_id),
	CONSTRAINT claims_claimant_id_fkey FOREIGN KEY (claimant_id) REFERENCES eoc.claimants(claimant_id),
	CONSTRAINT claims_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES eoc.policies(policy_id)
);
CREATE INDEX idx_claims_claimant ON eoc.claims USING btree (claimant_id);
CREATE INDEX idx_claims_correlation ON eoc.claims USING btree (correlation_id);
CREATE INDEX idx_claims_policy ON eoc.claims USING btree (policy_id);
CREATE INDEX idx_claims_status ON eoc.claims USING btree (status);


-- eoc.documents definition

-- Drop table

-- DROP TABLE eoc.documents;

CREATE TABLE eoc.documents (
	document_id text NOT NULL,
	claim_id text NULL,
	claimant_id text NULL,
	filename text NOT NULL,
	file_type text NULL,
	storage_path text NULL,
	ocr_status text DEFAULT 'pending'::text NULL,
	extracted_text text NULL,
	classification text NULL,
	validation_status text DEFAULT 'pending'::text NULL,
	uploaded_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	processed_at timestamp NULL,
	correlation_id text NULL,
	CONSTRAINT documents_pkey PRIMARY KEY (document_id),
	CONSTRAINT documents_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES eoc.claims(claim_id),
	CONSTRAINT documents_claimant_id_fkey FOREIGN KEY (claimant_id) REFERENCES eoc.claimants(claimant_id)
);
CREATE INDEX idx_documents_claim ON eoc.documents USING btree (claim_id);
CREATE INDEX idx_documents_ocr_status ON eoc.documents USING btree (ocr_status);


-- eoc.incident_alerts definition

-- Drop table

-- DROP TABLE eoc.incident_alerts;

CREATE TABLE eoc.incident_alerts (
	alert_id text NOT NULL,
	alert_type text NOT NULL,
	"source" text NULL,
	severity text DEFAULT 'medium'::text NULL,
	description text NULL,
	risk_score float8 NULL,
	related_claim_id text NULL,
	status text DEFAULT 'open'::text NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	correlation_id text NULL,
	CONSTRAINT incident_alerts_pkey PRIMARY KEY (alert_id),
	CONSTRAINT incident_alerts_related_claim_id_fkey FOREIGN KEY (related_claim_id) REFERENCES eoc.claims(claim_id)
);
CREATE INDEX idx_incidents_severity ON eoc.incident_alerts USING btree (severity);
CREATE INDEX idx_incidents_type ON eoc.incident_alerts USING btree (alert_type);


-- eoc.routing_decisions definition

-- Drop table

-- DROP TABLE eoc.routing_decisions;

CREATE TABLE eoc.routing_decisions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	session_id text NOT NULL,
	turn_id int8 NULL,
	selected_model text NULL,
	routing_reason text NULL,
	complexity_score float8 NULL,
	governance_score float8 NULL,
	prompt_hash text NULL,
	metadata jsonb NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT routing_decisions_pkey PRIMARY KEY (id),
	CONSTRAINT routing_decisions_session_id_fkey FOREIGN KEY (session_id) REFERENCES eoc.sessions(session_id),
	CONSTRAINT routing_decisions_turn_id_fkey FOREIGN KEY (turn_id) REFERENCES eoc.session_turns(id)
);


-- eoc.adjudication_records definition

-- Drop table

-- DROP TABLE eoc.adjudication_records;

CREATE TABLE eoc.adjudication_records (
	adjudication_id text NOT NULL,
	claim_id text NULL,
	event_id text NULL,
	decision text NOT NULL,
	confidence_score float8 NOT NULL,
	rationale text NULL,
	model_id text NULL,
	model_provider text NULL,
	prompt_hash text NULL,
	response_hash text NULL,
	disposition text NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	correlation_id text NULL,
	CONSTRAINT adjudication_records_pkey PRIMARY KEY (adjudication_id),
	CONSTRAINT adjudication_records_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES eoc.claims(claim_id)
);
CREATE INDEX idx_adjudication_claim ON eoc.adjudication_records USING btree (claim_id);
CREATE INDEX idx_adjudication_correlation ON eoc.adjudication_records USING btree (correlation_id);